#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env elk-data"

chown -R "$app:$app" "$install_dir"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app... (this may take a while)"

pushd $install_dir
    ynh_hide_warnings corepack enable
    ynh_hide_warnings ynh_exec_as_app pnpm i --frozen-lockfile --ignore-scripts
    ynh_hide_warnings ynh_exec_as_app pnpm nuxt prepare
    ynh_hide_warnings ynh_exec_as_app pnpm i --frozen-lockfile
    ynh_hide_warnings ynh_exec_as_app pnpm stale-dep -u 
    ynh_hide_warnings ynh_exec_as_app pnpm simple-git-hooks 
    ynh_hide_warnings ynh_exec_as_app pnpm nuxi prepare 
    ynh_hide_warnings ynh_exec_as_app pnpm nr prepare-translation-status 
    ynh_hide_warnings ynh_exec_as_app pnpm tsx scripts/prepare.ts
    ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=3000" pnpm build
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="nimble Mastodon Web client" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="Listening on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed."
